### ISSUE TITLE
How to remove (Err-Category: NotSpecified)

### ISSUE THREAD

**Issue by abaganuv** [echalone/TUN#1]
Hello
How can I remove the (Err-Category: NotSpecified) from the log?
Tried with -NoErrorDetails

**Comment by echalone** [comment]
Hi, this is currently not possible, this information will always be logged.
I see that this might be a bit confusing since it's listed in "Error-Details" in the logs, but the NoErrorDetails switch will only omit the information about the script name, the script line and the offset in the line that caused the error as well as the line that caused the error itself, it will still include the information logged as "Error-Details" in the logs.

**Comment by abaganuv** [comment]
Thank you
More 3 issues:
Why the timestamp in the log is as UTC? how to convert it to my time zone?
The name of the log is not right. 
If I create a log with name test1 this is the result: ae27a1.log
Start-Log -LogPath 'C:\Logs' -LogName 'test1'

How can I write also to the log and also to the console for debug of information?

**Comment by echalone** [comment]
Only UTC timestamps are supported for now (it often helps with time-zone differences between servers or summer/winter time changes).
But I've added a feature request issue for this and the Error Category so I remember it if I ever get to expand this module ;)

About the log name:
I've written it in the documentation here: https://github.com/echalone/TUN/blob/master/PowerShell/Modules/TUN.Logging/TUN.Logging.md#-logname
The -LogName parameter will be interpreted as a datetime format string, according to the C# DateTime.ToString method (which is desribed here: https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings). This means that "t" will be changed to "a" or "p" for "am" or "pm" and "s" will be changed to the current second of the minute, in this case second 27. To change that either escape the t's and s's with a backslash, so that would make it -LogName '\te\s\t1", or what will probably be easier for you is to just use the additional parameter -NoDateTimeFormat and it will take the -LogName parameter as is and create a file called "test1"

**Comment by echalone** [comment]
Closing issue, related feature request has been created
